---
# =============================================================================
# MariaDB Galera Cluster - Main Deployment Playbook
# =============================================================================
# Usage:
#   ansible-playbook -i inventory/hosts.yml deploy.yml
#
# Tags:
#   --tags mariadb    # Deploy only MariaDB nodes
#   --tags haproxy    # Deploy only HAProxy load balancers
#   --tags garbd      # Deploy only Galera Arbitrator nodes
# =============================================================================

- name: Validate Configuration
  hosts: localhost
  gather_facts: false
  tags: [always]
  tasks:
    - name: Validate node count is odd (recommended)
      ansible.builtin.debug:
        msg: >-
          WARNING: You have {{ mariadb_nodes | length }} MariaDB nodes.
          An odd number of nodes is recommended for proper quorum.
          Consider adding/removing a node or enabling garbd.
      when: (mariadb_nodes | length) % 2 == 0 and not garbd_enabled

    - name: Validate minimum node count
      ansible.builtin.fail:
        msg: "Minimum 2 MariaDB nodes required. You have {{ mariadb_nodes | length }}."
      when: mariadb_nodes | length < 2

    - name: Validate garbd configuration
      ansible.builtin.fail:
        msg: "garbd_enabled is true but garbd_nodes is empty. Define at least one garbd node."
      when: garbd_enabled and (garbd_nodes | length == 0)

    - name: Display deployment summary
      ansible.builtin.debug:
        msg: |
          ============================================
          MariaDB Galera Cluster Deployment Summary
          ============================================
          Cluster Name: {{ cluster_name }}
          MariaDB Nodes: {{ mariadb_nodes | length }}
          {% for node in mariadb_nodes %}
            - {{ node.name }}: {{ node.ip }}
          {% endfor %}
          HAProxy Nodes: {{ haproxy_nodes | length }}
          {% for node in haproxy_nodes %}
            - {{ node.name }}: {{ node.ip }}
          {% endfor %}
          Garbd Enabled: {{ garbd_enabled }}
          {% if garbd_enabled %}
          Garbd Nodes: {{ garbd_nodes | length }}
          {% for node in garbd_nodes %}
            - {{ node.name }}: {{ node.ip }}
          {% endfor %}
          {% endif %}
          SST Method: {{ sst_method }}
          ============================================

- name: Build Dynamic Inventory
  hosts: localhost
  gather_facts: false
  tags: [always]
  tasks:
    - name: Add MariaDB nodes
      ansible.builtin.add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        groups: mariadb
        server_id: "{{ idx + 1 }}"
        node_ip: "{{ item.ip }}"
        node_name: "{{ item.name }}"
      loop: "{{ mariadb_nodes }}"
      loop_control:
        index_var: idx

    - name: Add HAProxy nodes
      ansible.builtin.add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        groups: loadbalancers
        node_ip: "{{ item.ip }}"
        node_name: "{{ item.name }}"
      loop: "{{ haproxy_nodes }}"
      when: haproxy_nodes | length > 0

    - name: Add Garbd nodes
      ansible.builtin.add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        groups: garbd
        node_ip: "{{ item.ip }}"
        node_name: "{{ item.name }}"
      loop: "{{ garbd_nodes }}"
      when: garbd_enabled and garbd_nodes | length > 0

- name: Deploy MariaDB Galera Cluster
  hosts: mariadb
  become: true
  gather_facts: true
  serial: 1
  tags: [mariadb]
  roles:
    - mariadb_galera

- name: Bootstrap Galera Cluster
  hosts: mariadb[0]
  become: true
  gather_facts: false
  tags: [mariadb, bootstrap]
  tasks:
    - name: Check if cluster is running
      ansible.builtin.shell: |
        mariadb -u root -p'{{ mariadb_root_password }}' -e "SHOW STATUS LIKE 'wsrep_cluster_size';" 2>/dev/null | grep -oP '\d+' || echo "0"
      register: cluster_size_check
      changed_when: false
      failed_when: false
      no_log: true

    - name: Bootstrap cluster if not running
      when: cluster_size_check.stdout | int < 1
      block:
        - name: Stop MariaDB
          ansible.builtin.systemd:
            name: mariadb
            state: stopped

        - name: Bootstrap new cluster
          ansible.builtin.command: galera_new_cluster

        - name: Wait for bootstrap node
          ansible.builtin.wait_for:
            port: "{{ mysql_port }}"
            host: "{{ node_ip }}"
            delay: 5
            timeout: 60

- name: Start Remaining MariaDB Nodes
  hosts: mariadb[1:]
  become: true
  gather_facts: false
  serial: 1
  tags: [mariadb]
  tasks:
    - name: Start MariaDB
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: true

    - name: Wait for sync
      ansible.builtin.shell: |
        mariadb -u root -p'{{ mariadb_root_password }}' -e "SHOW STATUS LIKE 'wsrep_local_state_comment';" 2>/dev/null | grep -i synced
      register: sync_status
      until: sync_status.rc == 0
      retries: 30
      delay: 10
      changed_when: false
      no_log: true

- name: Secure Cluster and Create Admin User
  hosts: mariadb[0]
  become: true
  gather_facts: false
  tags: [mariadb, secure]
  tasks:
    - name: Set root password
      community.mysql.mysql_user:
        name: root
        password: "{{ mariadb_root_password }}"
        host_all: true
        login_unix_socket: /run/mysqld/mysqld.sock
        state: present
      no_log: true
      ignore_errors: true

    - name: Create admin user
      community.mysql.mysql_user:
        name: "{{ admin_user }}"
        password: "{{ admin_password }}"
        host: "%"
        priv: "*.*:ALL,GRANT"
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_unix_socket: /run/mysqld/mysqld.sock
        state: present
      no_log: true

    - name: Create SST user
      community.mysql.mysql_user:
        name: "{{ sst_user }}"
        password: "{{ sst_password }}"
        host: "localhost"
        priv: "*.*:RELOAD,PROCESS,LOCK TABLES,REPLICATION CLIENT"
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_unix_socket: /run/mysqld/mysqld.sock
        state: present
      when: sst_method == "mariabackup"
      no_log: true

    - name: Remove anonymous users
      community.mysql.mysql_user:
        name: ""
        host_all: true
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_unix_socket: /run/mysqld/mysqld.sock
        state: absent
      no_log: true

    - name: Remove test database
      community.mysql.mysql_db:
        name: test
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_unix_socket: /run/mysqld/mysqld.sock
        state: absent
      no_log: true

- name: Deploy Galera Arbitrator
  hosts: garbd
  become: true
  gather_facts: true
  tags: [garbd]
  when: garbd_enabled
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Galera Arbitrator
      ansible.builtin.apt:
        name: galera-arbitrator-4
        state: present

    - name: Configure Galera Arbitrator
      ansible.builtin.template:
        src: roles/mariadb_galera/templates/garb.j2
        dest: /etc/default/garb
        mode: "0644"
      notify: Restart garbd

    - name: Start garbd
      ansible.builtin.systemd:
        name: garb
        state: started
        enabled: true

  handlers:
    - name: Restart garbd
      ansible.builtin.systemd:
        name: garb
        state: restarted

- name: Deploy HAProxy Load Balancers
  hosts: loadbalancers
  become: true
  gather_facts: true
  serial: 1
  tags: [haproxy]
  when: haproxy_nodes | length > 0
  roles:
    - haproxy

- name: Verify Cluster Status
  hosts: mariadb[0]
  become: true
  gather_facts: false
  tags: [verify]
  tasks:
    - name: Get cluster size
      ansible.builtin.shell: |
        mariadb -u {{ admin_user }} -p'{{ admin_password }}' -e "SHOW STATUS LIKE 'wsrep_cluster_size';" 2>/dev/null | tail -1 | awk '{print $2}'
      register: final_cluster_size
      changed_when: false
      no_log: true

    - name: Display status
      ansible.builtin.debug:
        msg: |
          Deployment Complete!
          Cluster Size: {{ final_cluster_size.stdout }}
          Connect: mysql -h {{ haproxy_nodes[0].ip if haproxy_nodes | length > 0 else mariadb_nodes[0].ip }} -u {{ admin_user }} -p
